/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neaterbits_displayserver_render_cairo_CairoNative */

#ifndef _Included_com_neaterbits_displayserver_render_cairo_CairoNative
#define _Included_com_neaterbits_displayserver_render_cairo_CairoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_set_source_rgb
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1set_1source_1rgb
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_set_fill_rule
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1set_1fill_1rule
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_fill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1fill
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_paint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1paint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_stroke
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1stroke
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_stroke_preserve
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1stroke_1preserve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_new_path
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1new_1path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_move_to
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1move_1to
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_rel_move_to
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1rel_1move_1to
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_line_to
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1line_1to
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_rel_line_to
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1rel_1line_1to
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_rectangle
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1rectangle
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_surface_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1surface_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_CairoNative
 * Method:    cairo_surface_flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_CairoNative_cairo_1surface_1flush
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
