/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neaterbits_displayserver_render_cairo_xcb_XCBNative */

#ifndef _Included_com_neaterbits_displayserver_render_cairo_xcb_XCBNative
#define _Included_com_neaterbits_displayserver_render_cairo_xcb_XCBNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    xcb_connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_xcb_1connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    xcb_connect_display
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_xcb_1connect_1display
  (JNIEnv *, jclass, jstring, jstring, jbyteArray);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    xcb_disconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_xcb_1disconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    xcb_flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_xcb_1flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    xcb_get_setup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_xcb_1get_1setup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    setup_get_screens
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_setup_1get_1screens
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    screen_get_depths
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_screen_1get_1depths
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    depth_get_depth
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_depth_1get_1depth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    depth_get_visuals
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_depth_1get_1visuals
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_visual_id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1visual_1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_class
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1class
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_bits_per_rgb_value
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1bits_1per_1rgb_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_colormap_entries
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1colormap_1entries
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_red_mask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1red_1mask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_green_mask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1green_1mask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    visual_get_blue_mask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_visual_1get_1blue_1mask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_neaterbits_displayserver_render_cairo_xcb_XCBNative
 * Method:    cairo_create_xcb_surface
 * Signature: (JIJII)J
 */
JNIEXPORT jlong JNICALL Java_com_neaterbits_displayserver_render_cairo_xcb_XCBNative_cairo_1create_1xcb_1surface
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
